### ISSUE TITLE
Crate and Npgsql in the same app?

### ISSUE THREAD

**Issue by hlngo** [crate/npgsql-cratedb#7]
When creating a new app, Create requires to do the type mapping either at global level:
`CrateDbDatabaseInfo.AddCrateDbSpecificTypeMappings(NpgsqlConnection.GlobalTypeMapper);`

or do the same thing for connection:
`CrateDbDatabaseInfo.AddCrateDbSpecificTypeMappings(con.TypeMapper);`

If I use the global approach, is it safe to connect to an PostgreSQL server after doing that? The second approach has a significant performance hit, why is that?

**Comment by mikethebeer** [comment]
You should be fine if you go with the global approach. It should be possible to create multiple connections to different databases in prallel because when it connects it detects the database automatically and choses the correct type mappings.

However, it sounds a bit strange that you investigated a huge performance decrease if you apply the type mappings for each connection separately. Probably @apircher has more insights why this could be the case.

**Comment by hlngo** [comment]
@apircher Thanks for the detailed explanation. All makes sense.

**Comment by apircher** [comment]
I made some changes in the following branch: https://github.com/crate/npgsql-cratedb/tree/a/adapttypemappings 

In that branch, the `CrateDbDatabaseInfo.AddCrateDbSpecificTypeMappings`-method is not needed anymore and the performance is also improved. 

But it depends on some changes to npgsql which are contained in this PR: https://github.com/npgsql/npgsql/pull/1938

**Comment by hlngo** [comment]
@apircher Is there any reason that you don't merge this one to dev branch?

**Comment by apircher** [comment]
@hlngo I guess we can merge that pretty soon. But since this commit https://github.com/crate/npgsql-cratedb/commit/2d1027ddf717fcd9d15396a514efe337d3dc7ba3 the dev branch depends on the official npgsql and because PR#1938 is not merged at this time, things would not work.

**Comment by hlngo** [comment]
@apircher things move really slow with the npgsql. Is there anything that can be done to speed up the process?

**Comment by monanllc** [comment]
This issue may help: https://github.com/npgsql/npgsql/issues/2186. The key is to make the ResetFactories public? https://github.com/npgsql/npgsql/blob/c362e1c996d432f1df7030af49966897c4e26f5a/src/Npgsql/NpgsqlDatabaseInfo.cs#L263

**Comment by roji** [comment]
Please see [this note](https://github.com/npgsql/npgsql/issues/2186#issuecomment-428455349) on the design of database info factories, and how to have multiple ones co-exist side-by-side in the same application. In a nutshell, the CrateDB factory is expected to detect CrateDB, and return null otherwise, allowing the regular PostgreSQL type loading to occur.

**Comment by monanllc** [comment]
A simple app connects to CrateDB first then fails to open a connection to postgresql. I have looked at the CrateDbDatabaseInfoFactory and see it follows what @roji suggested. Do you guys have any idea why it fails?

**Comment by apircher** [comment]
@monanllc Surely you already use separate connection objects to access the two databases - right? Or do you use a connection object to connect to CrateDB first, then close it again and then use the same object to open a connection to PostgreSQL? I guess that could cause some problems...

**Comment by monanllc** [comment]
@apircher I used 2 different connections with Pooling=False.

**Comment by monanllc** [comment]
Please see the code below. The exception is "Object reference not set to an instance of an object".
```
// Crate
NpgsqlDatabaseInfo.RegisterFactory(new CrateDbDatabaseInfoFactory());
string crateConStr = "Server=localhost;Port=54321;User ID=test;Password=test;Timeout=0;Command Timeout=0;Pooling=False;";
using (var crateCon = new NpgsqlConnection(crateConStr))
{
    crateCon.Open();
    crateCon.TypeMapper.UseCrateDbObjectHandler();
    DataTable resultTable = null;
    using (var cmd = new NpgsqlCommand("SELECT * FROM doc.tweets LIMIT 100;", crateCon))
    {
        using (var adapter = new NpgsqlDataAdapter(cmd))
        {
            resultTable = new DataTable();
            resultTable.BeginLoadData();
            adapter.Fill(resultTable);
            resultTable.EndLoadData();
        }
    }
    //dataGrid.ItemsSource = resultTable.DefaultView;
}

// Connect to Posgresql
string pgConStr = "Database=; Host=localhost; Port=5432; Username=postgres; Password=test; Pooling=False;";
using (var pgCon = new NpgsqlConnection(pgConStr))
{
    try
    {
        pgCon.Open();  // throws "Object reference not set to an instance of an object"
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.Message);
    }
}
```

**Comment by monanllc** [comment]
```
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
   at Npgsql.NpgsqlDatabaseInfo.<Load>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<LoadDatabaseInfo>d__150.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at WpfApp1.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\Monan\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 63
```

**Comment by apircher** [comment]
@monanllc, We have just rebased our fork to integrate the latest changes of the npgsql team. Updated nuget packages should be available tomorrow.

The stacktrace looks like there is a null value in the factories list. Maybe the problem has been fixed by the npgsql team in the meantime. Would you mind trying the latest version again?

**Comment by monanllc** [comment]
@apircher I will try it tomorrow when the nuget package available

**Comment by monanllc** [comment]
I can't connect to Crate with the latest version. Stack trace:
```
Exception thrown: 'System.MethodAccessException' in mscorlib.dll
   at Npgsql.CrateDb.CrateDbDatabaseInfo.<CrateDbSpecificTypeMappings>d__27.MoveNext()
   at Npgsql.CrateDb.CrateDbDatabaseInfo.AdaptTypeMappings(IDictionary`2 mappings)
   at Npgsql.TypeMapping.ConnectorTypeMapper.BindTypes()
   at Npgsql.NpgsqlConnector.<LoadDatabaseInfo>d__150.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at WpfApp1.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\Monan\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 42
```

**Comment by apircher** [comment]
@monanllc Are you using Version 4.1.0-crate1 of the crate npgsql fork?

In that version we made npgsqls TimestampHandlerFactory public so we can access it in the plugin. The MethodAccessException looks as if you are loading the original npgsql or an older version of the crate io fork.

**Comment by monanllc** [comment]
@apircher I am not sure. I uninstalled the nuget package and then install the new version. It's the same error.

**Comment by apircher** [comment]
@monanllc Sorry for the hassle. Our new versioning of the fork package does not work. Nuget interprets the Version 4.1.0-crate1 as a pre-release version and so - probably because the fork package is also not listed in nuget search results - the new fork package is never installed. Nuget installs the latest 4.1.0 instead and in that version the TimeStampHandlerFactory is still private.

We will redeploy the fork package soon with a new versioning.

**Comment by roji** [comment]
@apircher this is off-topic, but:

1. If need to have a public TimeStampHandlerFactory, I'd definitely accept a PR that does this. It can be released in a patch version (so quite quickly).
2. Otherwise, another option is for you to simply copy the code into the CrateDB assembly. It's a bit of duplication but it's not the end of the world.

Doing the above may allow you to stop forking Npgsql (unless you're also doing it to setup your own DatabaseInfoFactory). I'm also a bit confused on the version - there's no released 4.1.0 yet, so I'm guess you're releasing based on our dev branch? If so that could be a bad idea as that branch is expected to be quite unstable...

**Comment by apircher** [comment]
thank you @roji, I agree. We will soon switch to releasing from the master branch. We could probably create pre-release versions of the dev branch then.

The reason why we will continue forking Npgsql is [this commit](https://github.com/crate/npgsql/commit/3c9941d865ed20b0e8634607dc96f6cacc95b514) and [this one](https://github.com/crate/npgsql/commit/4d1d22a07d719f5a2d26bbbc3541ba795b6c27e5).

The first one already has a PR and we will probably create a PR for the second one soon.

**Comment by apircher** [comment]
@monanllc There are updated nuget packages available now. The crate fork of Npgsql is now published with a new package id and it´s own versioning - independent of Npgsql´s versioning. 

This should fix the `System.MethodAccessException` that is thrown when you call `NpgsqlConnection.Open`.

**Comment by monanllc** [comment]
@apircher I tried the latest build. Still have this error: 

```
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
   at Npgsql.NpgsqlDatabaseInfo.<Load>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<LoadDatabaseInfo>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at WpfApp1.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\Monan\source\repos\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 80
```

**Comment by apircher** [comment]
@monanllc sorry for the delay - I am currently working on another project. But @mikethebeer released new versions of the plugin and the fork yesterday and we currently can´t reproduce this issue. 
Are you maybe loading an older version from the GAC? Or the original npgsql? Does it work if you create a fresh test application?

**Comment by monanllc** [comment]
@apircher Sorry for the delay. As for this issue, it doesn't work even for a fresh app.

**Comment by kneth** [comment]
We have archived the repository. You can use the [stock driver](https://www.npgsql.org/) to connect to CrateDB version 4.2 or later.
